modLoader="javafml" #mandatory
loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
[[mods]] #mandatory
modId="xphealth" #mandatory
version="${file.jarVersion}" #mandatory
displayName="XR Health" #mandatory
logoFile="xphealth.png" #optional
credits="" #optional
authors="boterop" #optional
description='''
With this mod we will be able to use the experience in a better way.
Every time you increase your experience the amount of hearts will go up.
'''

[[dependencies.xphealth]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[40,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.xphealth]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
